/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 14_12914_8132.glb -T 
Files: 14_12914_8132.glb [32.13MB] > 14_12914_8132-transformed.glb [7.1MB] (78%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/14_12914_8132-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.building_HDB.geometry} material={nodes.building_HDB.material} />
    </group>
  )
}

useGLTF.preload('/14_12914_8132-transformed.glb')
